#!/bin/sh

# xinitrc runs automatically when you run startx.

# There are some small but important commands that need to be run when we start
# the graphical environment. There is a link to this file in ~/.xprofile
# because that file is run automatically if someone uses a display manager
# (login screen) and so they are needed there. To prevent doubling up commands,
# I source them here with the line below.

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi

# picom
picom -b

# xrandr
xrandr --output HDMI-0 --mode 2560x1440 --pos 0x0 --primary --rate 240
xrandr --output DP-0 --mode 2560x1440 --pos 2561x0 --rate 165

# Key Repeat / Auto-repeat behavior
xset r rate 400 32

# Activate dbus variables
dbus-update-activation-environment --all
dbus-launch ssh-agent dwm
